version: '3'

services: 
    app:
        build: .
        container_name: painel-admin-app
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/home/django/app
        ports: 
            - "8000:8000"
        depends_on: 
            - db
    db:
        image: postgres
        container_name: painel-db
        tty: true
        environment: 
            - POSTGRES_DB=painel_admin
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        volumes: 
            - painel-admin-pgdata:/var/lib/postgresql/data
volumes: 
    painel-admin-pgdata:
        external: true            

